language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
script:
- ./scripts/testserver.sh
- ./scripts/testonsauce.sh
env:
  global:
  - secure: ZxldMUNPjm7T/zGthCGvL2kbPLapcaJAj1VXYFw3he9TW4FG0H+E4u6/NEPSG5OdtG530NizguKJlbigmAN16eKaD+1MPkvBAY274RdFKBVv3Lemb1impM7VZC/zMOfDqmIPXYSzvp0Qgw1McS3W1x0Ub2arPS0CwW83LjackCQ=
  - secure: CyolMw3r+ezNBciIvy7qEBGwXNuKB5zhbB+p4x0jWNXOoimT2LY1ParJ+NavBB9fbedMxn2qGQxAAhGtgjg/x2TFdI5V80hDHb3rnLvGEUM54/HioAuTr7cyp425ujIdr/b5vg6w1yb2FE0LTcfpuqaHRmKevxrYoCi8b0ETak8=
