language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
script:
- ./scripts/testserver.sh
- ./scripts/testonsauce.sh
env:
  global:
  - secure: lGdhMVuOkvBAPanf/7uizNW3E4/kFlHiuO2ByjTpLiD2A7HDwMXZ9kV2qbbr/E634n+v7Dwwk3Nprf/Rho4bDfb8moeMb24b9Dg1I5W7uOjdVB57KBtEE2YAjGZv49eORLV2u0kHC9qy9Z1f8wiVz7xUQvXpVFjJQzArcW9/3Ks=
  - secure: BEU3WBOgk8JwKpt1sbOpaLSRNTmYcm7vl+z4MO9hEPAeeHNYOjF1h3ZHsIzP5YzIgq4L40zB+prD4WvWA0kK2RGuWxe2YNhyvCZzJgY7la4uHgOpayPiCe+UsjLvA5NYKjRYd7qE5nbkdzO63LLbsrfA4/XRTXCs3mx3innmoxI=
