language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
script:
- ./scripts/testserver.sh
- ./scripts/testonsauce.sh
env:
  global:
  - SAUCE_USERNAME=christriddle
  - SAUCE_ACCESS_KEY=08550a52-96a8-4de4-acdd-e09a1071122c'
