language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: KxU52CO+NwAVTghagvLnfmjLX4vqJ/eAbBVAEzcd/j2ZEP5LULBmDNt/9zArBpPZssH6TfUcmCxNOX1XP0qWzCS+XQX7G6Rpg68MEjOd9YCg6HMAM3Cnhjikbt0EiTSX7NqGz9l1G+/rrxdfbJDY2cN5mxCZ/+0VxHrMBbaG97g=
    - secure: fZ/cGV9GRx1S61ZH7Nay0n3r9qlzISiiC72dUQqx/YTKfMVJfQhYy/Oyq60cAEQ60Zuna2yOH/+s8kAr2GQn9lG20vuLz5BFQf5wud7a7EQ5fwKIzHFfX6WK5qOJ9Dq4DkfCSz7Fxvb4XVYfZl37Q5mfCMPUJXpEFoHd+kT4nyE=

addons:
  sauce_connect: true

script:
  - ./scripts/testserver.sh
  - ./scripts/testonsauce.sh
